name: NodeJS build and package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm install -g vsce
        
    - name: Pretest
      run: |
        npm install -g eslint
        npm run pretest
        
#    - name: Map insights to cat
#      run: |
#        shopt -s expand_aliases
#        alias insights="cat"
        
#    - name: Test
#      run: |
#        npm install -g eslint
#        npm test
    
    - name: Package
      run:
        vsce package
        
    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: vsix
        path: vscode-cppinsights-*.vsix
